spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts_db
    username: user
    password: password
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      root: INFO

server:
  port: 8080
